# Generated by Django 2.2.5 on 2019-09-22 12:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)])),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('year', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('month', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('day', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
            ],
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('face_encoding', models.TextField(blank=True, null=True)),
                ('smile', models.FloatField(blank=True, default=0.0)),
                ('anger', models.FloatField(blank=True, default=0.0)),
                ('contempt', models.FloatField(blank=True, default=0.0)),
                ('disgust', models.FloatField(blank=True, default=0.0)),
                ('fear', models.FloatField(blank=True, default=0.0)),
                ('happiness', models.FloatField(blank=True, default=0.0)),
                ('neutral', models.FloatField(blank=True, default=0.0)),
                ('sadness', models.FloatField(blank=True, default=0.0)),
                ('surprise', models.FloatField(blank=True, default=0.0)),
                ('age', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='controller.AgeGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('name', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('faces', models.ManyToManyField(to='controller.Face')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=150)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(default='default', upload_to='images')),
                ('face_analyzed', models.BooleanField(default=False)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controller.Date')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controller.Place')),
            ],
        ),
        migrations.AddField(
            model_name='face',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='controller.Gender'),
        ),
        migrations.AddField(
            model_name='face',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controller.Image'),
        ),
    ]
