# Generated by Django 2.2.5 on 2019-09-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
