# Generated by Django 2.2.10 on 2020-05-13 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20191024_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='service_face_encoding_analyzing_startdate',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='image',
            name='service_face_location_analyzing_startdate',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
