# Generated by Django 2.2.5 on 2019-09-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0003_auto_20190923_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='face_analyzed',
            new_name='service_face_encoding_analyzed',
        ),
    ]
