# Generated by Django 2.2.5 on 2019-09-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_auto_20190924_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='face_location_h',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='face',
            name='face_location_w',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='face',
            name='face_location_x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='face',
            name='face_location_y',
            field=models.IntegerField(default=0),
        ),
    ]
