# Generated by Django 2.2.10 on 2020-05-15 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_auto_20200513_0215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gender',
            new_name='Sex',
        ),
        migrations.RenameField(
            model_name='face',
            old_name='gender',
            new_name='sex',
        ),
        migrations.AddField(
            model_name='face',
            name='service_sex_detection_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='face',
            name='service_sex_detection_analyzing_startdate',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
