# Generated by Django 2.2.10 on 2020-05-18 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_auto_20200515_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='service_age_prediction_analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='face',
            name='service_age_prediction_analyzing_startdate',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='face',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='AgeGroup',
        ),
    ]
