# Generated by Django 2.2.5 on 2019-09-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0005_auto_20190928_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='service_face_rect_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
