# Generated by Django 2.2.5 on 2019-10-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0007_auto_20190929_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='service_face_encoding_analyzed',
        ),
        migrations.AddField(
            model_name='face',
            name='service_face_encoding_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
