# Generated by Django 2.2.5 on 2019-10-06 18:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0008_auto_20191006_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
