# Generated by Django 2.2.5 on 2019-10-06 18:17

import controller.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0009_auto_20191006_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='id',
            field=models.CharField(default=controller.models.uuid4_str, max_length=36, primary_key=True, serialize=False),
        ),
    ]
