version: '3'
services:
  service_face_location:
    build: services/face_location
    volumes:
      - "./services/face_location:/code"
    env_file:
      - worker.env
  
  service_face_encoding:
    build: services/face_encoding
    volumes:
      - "./services/face_encoding:/code"
    env_file:
      - worker.env
  
  service_sex_detection:
    build: services/sex_detection
    env_file:
      - worker.env
  
  service_age_prediction:
    build: services/age_prediction
    env_file:
      - worker.env
