FROM nvcr.io/nvidia/l4t-tensorflow:r32.4.2-tf1.15-py3

RUN apt install -y libhdf5-dev

WORKDIR /code

RUN pip3 install pillow

COPY ./model.py .
COPY ./sex_detection.h5 .
COPY ./sex_detection.py .

CMD [ "python3", "sex_detection.py" ]
