FROM nvidia/cuda

RUN apt update
RUN apt install -y python3.7-dev python3-pip build-essential cmake curl

# Install pip
RUN curl -kL https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN sudo python3

COPY ./requirements.txt /
RUN pip3 install -r requirements.txt

ENV GB_GPU=True
WORKDIR /code
CMD ["python3.7", "face_location.py"]
