FROM nvidia/cuda

RUN apt update
RUN apt install -y python3.7-dev python3.7 python3-pip build-essential cmake curl

COPY ./requirements.txt /
RUN python3.7 -m pip install -r requirements.txt

ENV GB_GPU=True
WORKDIR /code
CMD ["python3.7", "face_location.py"]
