FROM nvidia/cuda:10.1-cudnn7-devel

RUN apt update
RUN apt install -y python3.7-dev python3.7 python3-pip python3-setuptools build-essential cmake curl gcc g++ make git libopenblas-dev liblapack-dev

# cudnn path
RUN cp -a /usr/include/cudnn.h /usr/local/cuda/include
RUN cp -a /usr/lib/x86_64-linux-gnu/libcudnn* /usr/local/cuda/lib64
RUN chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*

# build dlib
RUN git clone https://github.com/davisking/dlib
RUN mkdir /dlib/build

RUN CUDA_PATH="/usr/local/cuda-10"
RUN CFLAGS="-I/usr/local/cuda/include"
RUN LDFLAGS="-L/usr/local/cuda-10.0/lib64"

WORKDIR /dlib
RUN cmake -DUSE_AVX_INSTRUCTIONS=YES -DLIB_USE_CUDA=YES
RUN cmake --build .
RUN make install



RUN python3.7 setup.py build
RUN python3.7 setup.py install


WORKDIR /
COPY ./requirements.txt /
RUN python3.7 -m pip install -r requirements.txt

ENV GB_GPU=True
WORKDIR /code
CMD ["python3.7", "face_location.py"]
