FROM nvidia/cuda
RUN apt update
RUN apt install -y python3.7-dev python3-pip build-essential cmake curl

# Install pip for python3.7
RUN curl -kL https://bootstrap.pypa.io/get-pip.py | python3.7

COPY ./requirements.txt /
RUN pip3 install -r requirements.txt

WORKDIR /code
CMD [ "python3.7", "face_encoding.py" ]
