FROM python:3.7-slim-stretch

# Install dependencies
RUN apt update
RUN apt install -y build-essential cmake
# Install Pillow dependencies
RUN apt install -y libtiff5-dev libjpeg-dev libopenjp2-7-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
    libharfbuzz-dev libfribidi-dev libxcb1-dev
# Install dlib dependencies
RUN apt install -y cmake gfortran graphicsmagick libgraphicsmagick1-dev libatlas-dev libavcodec-dev libavformat-dev libboost-all-dev libgtk2.0-dev libjpeg-dev liblapack-dev libswscale-dev python-dev python-protobuf software-properties-common


# Install python dependencies
COPY ./requirements.txt /
RUN pip install -r requirements.txt

WORKDIR /code
CMD [ "python", "face_encoding.py" ]
